/*
 * games 테이블 시드 (games.json 기준)
 * Supabase → SQL Editor 에 붙여넣고 Run
 *
 * 주의: 기존 games 행을 지웁니다. added_by 는 기본 김하늘, 이름이 「딥씨 크루」인 행만 NULL.
 */

DELETE FROM public.games;

INSERT INTO public.games (
  name,
  difficulty,
  genres,
  min_players,
  max_players_raw,
  max_players_kind,
  max_players_value,
  beginner_friendly,
  notes,
  extra_notes,
  added_by
)
VALUES
  ('갱오브다이스', 1, ARRAY['주사위']::text[], NULL, '4', 'number', '4', true, '주사위로 하는 치킨게임', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('노땡스', 1, ARRAY['기타']::text[], NULL, '7', 'number', '7', true, '마이너스 경매', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('더 마인드', 1, ARRAY['카드 클라이밍']::text[], NULL, '--', 'unknown', NULL, true, '침묵의 오름차순', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('돌진소녀', 1, ARRAY['기타']::text[], NULL, '4', 'number', '4', true, '순발력 게임', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('드림온', 1, ARRAY['기타']::text[], NULL, '4', 'number', '4', true, '스토리텔링 게임, 기억력+단합', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('딕싯', 1, ARRAY['기타']::text[], NULL, '6', 'number', '6', true, '그림 연상 퀴즈', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('라스베가스', 1, ARRAY['베팅']::text[], NULL, '5', 'number', '5', true, '주사위 도박게임', '김범기 선정 베스트 웰컴 게임(운+전략+적당한 인터랙션)', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('마헤', 1, ARRAY['주사위']::text[], NULL, '7', 'number', '7', true, '거북이 등에 업어하는 게임', '김범기 선정 베스트 웰컴 게임2(운+적당한 인터랙션)', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('모자가 아니잖아', 1, ARRAY['블러핑']::text[], NULL, '11이상', 'min_plus', '11', true, '바퀴벌레 포커랑 비슷, 웃으며 할 수 있는 기억력 게임', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('바퀴벌레 포커', 1, ARRAY['블러핑']::text[], NULL, '4', 'number', '4', false, '파리 투나잇', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('반디도', 1, ARRAY['기타']::text[], NULL, '--', 'unknown', NULL, true, '협력하여 도둑 잡기', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('아브라카 왓', 1, ARRAY['기타']::text[], NULL, '4', 'number', '4', true, '내가 갖고 있는 마법은 어떤 걸까', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('인간 vs 돌', 1, ARRAY['기타']::text[], NULL, '11이상', 'min_plus', '11', true, '상식 퀴즈', '가볍게 웃으면서 즐길 수 있음', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('인사이더', 1, ARRAY['기타']::text[], NULL, '8', 'number', '8', true, '답을 유도하는 질문자를 찾아라', '마피아+스무고개', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('잉카의황금', 1, ARRAY['블러핑']::text[], NULL, '8', 'number', '8', false, '인생은 끝없는 모험과 도박', '혼자 독식하거나, 적당히 먹고 빠지거나.', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('저스트원', 1, ARRAY['기타']::text[], NULL, '--', 'unknown', NULL, true, '단어 힌트 겹치지 않게 주기', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('젝스님트', 1, ARRAY['기타']::text[], NULL, '--', 'unknown', NULL, true, '소고기를 누군가 먹어주겠지', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('코드네임', 1, ARRAY['기타']::text[], NULL, '--', 'unknown', NULL, false, '연상 단어 맞히기', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('탑텐TV', 1, ARRAY['협력']::text[], NULL, '9', 'number', '9', true, '동일한 질문, 서로 다른 답변', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('텔레스트레이션', 1, ARRAY['기타']::text[], NULL, '--', 'unknown', NULL, true, '오프라인 캐치마인드', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('펭귄파티', 1, ARRAY['기타']::text[], NULL, '6', 'number', '6', true, '내 카드를 내려놓을 수 있는 곳이 또 어디 있지?', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('후지플러시', 1, ARRAY['기타']::text[], NULL, '8', 'number', '8', true, '티끌 모아 태산', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('광란의 푸드트럭', 2, ARRAY['기타']::text[], NULL, '6', 'number', '6', false, '눈치 보고 푸드트럭 자리잡기', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('나나', 2, ARRAY['기타']::text[], NULL, '5', 'number', '5', false, '너의 기억력은?', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('달무티', 2, ARRAY['카드 클라이밍']::text[], NULL, '8', 'number', '8', true, '인생은 불공평합니다', '조서형 선정 베스트 웰컴 게임', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('러브레터', 2, ARRAY['기타']::text[], NULL, '4', 'number', '4', false, '러브레터를 전달하기 위해 목숨을 바치자', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('레지스탕스 쿠', 2, ARRAY['블러핑']::text[], NULL, '4', 'number', '4', false, '러브레터랑 비슷', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('문 립', 2, ARRAY['주사위']::text[], NULL, '4', 'number', '4', true, '등번호 달린 달 탐사 요원들', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('사보타지', 2, ARRAY['마피아']::text[], NULL, '10', 'number', '10', false, '광산에 들어간 광부들, 황금을 캐낼 수 있을까?', '광부들끼리도 은근한 경쟁이 있음', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('세븐원더스', 2, ARRAY['전략']::text[], NULL, '7', 'number', '7', false, '7인까지 가능한 전략게임, 생각보다 쉬움', '동엽님 추천 게임 (스플렌더 단체 버전 느낌)', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('셀레스티아', 2, ARRAY['블러핑']::text[], NULL, '6', 'number', '6', false, '블러핑과 협력의 적절한 조화', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('쉐도우 레이더스', 2, ARRAY['마피아']::text[], NULL, '10', 'number', '10', false, '뱅(BANG) 업그레이드 버전', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('스카우트', 2, ARRAY['카드 클라이밍']::text[], NULL, '4', 'number', '4', false, '너, 내 서커스이 되라!', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('시타델', 2, ARRAY['기타']::text[], NULL, '8', 'number', '8', false, '카드 드래프트의 묘미', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('아줄', 2, ARRAY['기타']::text[], NULL, '4', 'number', '4', true, '유리창 장식하기', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('위너스써클', 2, ARRAY['베팅']::text[], NULL, '6', 'number', '6', false, '인생 한 방 경마', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('착한녀석들', 2, ARRAY['블러핑']::text[], NULL, '8', 'number', '8', false, '적을 견제하면서 최대한 많은 돈을 얻어내라', '공격, 방어, 카드 선점까지 밸런스 좋은 게임', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('코요테', 2, ARRAY['기타']::text[], NULL, '10', 'number', '10', true, '덧셈을 잘해야 하는 눈치게임', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('퍼레이드', 2, ARRAY['기타']::text[], NULL, '6', 'number', '6', false, '나도 퍼레이드에 끼워줘', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('포세일', 2, ARRAY['베팅']::text[], NULL, '6', 'number', '6', false, '경매를 통해 돈을 벌자', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('노터치크라켄', 3, ARRAY['마피아']::text[], NULL, '8', 'number', '8', false, '작은 마피아', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('레지스탕스 아발론', 3, ARRAY['마피아']::text[], NULL, '10', 'number', '10', false, '이번 원정대는 누구야?', '멀린은 내가 할게', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('렉시오', 3, ARRAY['카드 클라이밍']::text[], NULL, '5', 'number', '5', false, '포커 족보를 이용한 달무티', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('모던아트', 3, ARRAY['베팅']::text[], NULL, '5', 'number', '5', false, '적절한 금액으로 작품을 사고 팔자', '꽤 어려운데, 재밌었던 기억', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('몰타의 관문', 3, ARRAY['덱 빌딩']::text[], NULL, '5', 'number', '5', false, '숫자를 모아 몬스터를 물리치자', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('뱅(BANG)', 3, ARRAY['마피아']::text[], NULL, '5', 'number', '5', false, '보안관을 도와 무법자를 제압하라!', '엄청 유명해서 다들 알지만, 조금 어려움', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('버건디의성', 3, ARRAY['전략']::text[], NULL, '4', 'number', '4', false, '어떤 테크를 타느냐에 따라 달라지는 게임', '뱃사람(장사), 땅 타일 배치 등', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('세일럼', 3, ARRAY['마피아']::text[], NULL, '11이상', 'min_plus', '11', false, '과거의 적이 현재의 팀이 된다. 마녀는 누구인가?', '독특한 마피아 게임', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('스컬킹', 3, ARRAY['트릭 테이킹']::text[], NULL, '6', 'number', '6', true, '해적왕이 되어보자', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('스페이스크루', 3, ARRAY['협력']::text[], NULL, '5', 'number', '5', false, '우주선에 제대로 된 신호를 보내야 해!', '하나비와 비슷, 조금 더 어려운 협동게임', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('시크릿 히틀러', 3, ARRAY['마피아']::text[], NULL, '10', 'number', '10', false, '저는 선량한 파시스트입니다', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('아임더보스', 3, ARRAY['협상']::text[], NULL, '6', 'number', '6', false, '내가 보스다', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('영리한 여우', 3, ARRAY['주사위']::text[], NULL, '4', 'number', '4', false, '어느 주사위를 골라야 이득일까', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('카탄(CATAN)', 3, ARRAY['협상']::text[], NULL, '4', 'number', '4', false, '가장 번성한 대지주가 되어보자', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('하나비', 3, ARRAY['협력']::text[], NULL, '4', 'number', '4', false, '멋진 불꽃놀이를 완성해보자', '3 ~ 5인 협동게임, 팀원 간 호흡이 중요', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('한밤의 늑대인간', 3, ARRAY['마피아']::text[], NULL, '10', 'number', '10', false, '밤이 한 번뿐인 마피아', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('훈트', 3, ARRAY['트릭 테이킹']::text[], NULL, '5', 'number', '5', false, '귀여운 일러스트, 그러나 알고 보면 뒤통수 치는 게임...', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('트라야누스', 3, ARRAY['전략']::text[], NULL, '4', 'number', '4', false, '로마 시대의 집정관이 되어 나라를 경영하라.', '세븐원더스처럼 룰이 간단하고 초심자도 즐길 수 있는 정도', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('리코셰로봇', 4, ARRAY['전략']::text[], NULL, '--', 'unknown', NULL, false, '직진 밖에 할 수 없는 우주선이 집으로 찾아오려면...', '취향 많이 타는 공대 게임', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('마이티', 4, ARRAY['트릭 테이킹']::text[], NULL, '5', 'number', '5', false, '트럼프 카드로 할 수 있는 베팅 & 트릭 테이킹 게임', '점수 계산 룰이 다양해서 조금 헷갈림', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('언더다크의 폭군들', 4, ARRAY['영향력']::text[], NULL, '4', 'number', '4', false, '[전략] 사령관이 되어서 최대한 많은 기지를 확보하라', '동엽님이 룰마해준 게임', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('언더랜드워', 4, ARRAY['전략']::text[], NULL, '4', 'number', '4', false, '이상한 나라의 앨리스 기반 워(War) 게임', '플레이 타임 약 2시간 이상', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('클랜오브칼레도니아', 4, ARRAY['영향력']::text[], NULL, NULL, 'unknown', NULL, false, '', '주용님 추천(?) 게임 - 아직 안해봄', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('테라포밍마스', 4, ARRAY['전략']::text[], NULL, '4', 'number', '4', false, '화성을 개척하고 숲과 도시를 건설하라', '룰 설명만 30분 넘게 걸림', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('튜링머신', 4, ARRAY['기타']::text[], NULL, '--', 'unknown', NULL, false, '암호학의 아버지, 앨런 튜링', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('티츄', 4, ARRAY['카드 클라이밍']::text[], NULL, '4', 'number', '4', false, '라지 티츄의 짜릿함', '', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('푸에르토리코', 4, ARRAY['전략']::text[], NULL, '5', 'number', '5', false, '많은 작물을 수출해보자. 위치 배정이 중요한 게임', '오랜 시간 왕좌를 지킨 고전 게임', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('가이아프로젝트', 4, ARRAY['영향력']::text[], NULL, '5', 'number', '5', false, '"우주"를 테라포밍하라.', '플레이 타임 2 ~ 3시간', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('파워그리드', 4, ARRAY['전략']::text[], NULL, '6', 'number', '6', false, '민영화된 미래 시대에서 전기를 많이 생산해야 한다.', '경매 기반, 포스트잇 + 펜 필수(간단한 계산해야 함)', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1)),
  ('세티', 4, ARRAY['전략']::text[], NULL, '4', 'number', '4', false, '', '아직 못 해봄 ㅠㅠ', (SELECT id FROM public.profiles WHERE display_name = '김하늘' LIMIT 1));
